# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: phpunit/phpunit:5.0.3

pipelines:
  default:
    - step:
        script:
          - composer --version
          - phpunit --version
          - composer install
          - vendor/bin/phpunit -v
